server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**

        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/parkings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
