spring:
  application:
    name: api-gateway
  config:
    import: configserver:
  cloud:
    config:
      uri: http://localhost:8888 # Config Server URL
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicle/**
        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/parking/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
