server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicle-service/**

        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/parking-service/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
