server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicle/**
        - id: parking-server
          uri: lb://parking-server
          predicates:
            - Path=/parking/**
        - id: payment-server
          uri: lb://payment-server
          predicates:
            - Path=/payment/**
