server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - GatewayJwt

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**
          filters:
            - GatewayJwt

        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/parkings/**
          filters:
            - GatewayJwt
            
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - GatewayJwt

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - GatewayJwt
jwt:
  secret: k0HgZ2Ff7I1N4eHV2RuYB6UYZgDY5X3Lk4zGuMVRTRH1QoAnzj5X9TZGf6R2AbMVqepnqQo/ErwdDbnLJ3vSsw==

app:
  base-url: http://localhost:8080   # ✅ added
