server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/spmsdb?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false  # ✅ added

  main:
    allow-bean-definition-overriding: true  # ✅ added
    allow-circular-references: true         # ✅ added
    
jwt:
  secret: Ey3q0Tb41rDzVo6Fy+JWmiXg7o+U4CD6HKWZ1v0U9c4rTzUv7On6YUzZ1M7YZIlCKMaGVwzHVE9XmDLg0cOszA==
app:
  base-url: http://localhost:8080   # ✅ added
