server:
  port: 8082

spring:
  application:
    name: vehicle-service
    
eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"


